'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import api from '@/lib/api';
import { formatRupiah } from '@/lib/format';

export default function HonorSlipPreviewPage() {
  const { tutorId }=useParams<{tutorId:string}>(); const search=useSearchParams(); const month=Number(search.get('month')||new Date().getMonth()+1); const year=Number(search.get('year')||new Date().getFullYear()); const [slip,setSlip]=useState<any>(null); const [error,setError]=useState('');
  useEffect(()=>{api.get('/honor/slip-summary',{params:{tutorId,month,year}}).then(r=>setSlip(r.data.data)).catch(e=>setError(e.response?.data?.message||'Gagal memuat Slip Honor.'));},[tutorId,month,year]);
  async function download(){try{const r=await api.get('/honor/slip.pdf',{params:{tutorId,month,year},responseType:'blob'});const url=URL.createObjectURL(new Blob([r.data],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download=`slip-honor-${month}-${year}.pdf`;a.click();URL.revokeObjectURL(url);}catch(e:any){setError(e.response?.data?.message||'Gagal membuat Slip Honor.');}}
  if(error)return <div className="space-y-3"><Link href={`/admin/recap/tutor/${tutorId}?month=${month}&year=${year}`} className="text-sm text-navy-900">← Kembali ke Detail</Link><p className="rounded bg-red-50 p-3 text-sm text-red-600">{error}</p></div>;
  if(!slip)return <p className="text-sm text-gray-500">Memuat preview Slip Honor...</p>;
  const period=new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date(year,month-1,1)); const printed=new Intl.DateTimeFormat('id-ID',{dateStyle:'long'}).format(new Date());
  return <div className="space-y-4"><div className="flex items-center justify-between"><Link href={`/admin/recap/tutor/${tutorId}?month=${month}&year=${year}`} className="text-sm font-medium text-navy-900">← Kembali ke Detail</Link><button onClick={download} className="rounded-md bg-navy-900 px-4 py-2 text-sm text-white">Download PDF</button></div><div className="overflow-x-auto pb-4"><article className="mx-auto min-h-[1075px] w-[760px] border border-gray-200 bg-white p-14 shadow-sm"><header className="border-b-2 border-navy-900 pb-6 text-center"><div className="mx-auto mb-3 flex h-11 w-11 items-center justify-center rounded-lg bg-navy-900 text-lg font-bold text-white">P</div><h1 className="text-2xl font-bold text-navy-900">{slip.settings.institutionName||slip.settings.systemName}</h1><p className="mt-5 text-lg font-bold text-navy-900">SLIP HONOR TENTOR</p><p className="mt-1 text-sm">Periode: <b>{period}</b></p></header><div className="mt-7 grid grid-cols-2 gap-6 text-sm"><p>Periode<br/><b>{period}</b><br/><br/>Tentor<br/><b>{slip.tutor.name}{slip.tutor.title?`, ${slip.tutor.title}`:''}</b></p><p className="text-right">Tanggal Cetak<br/><b>{printed}</b></p></div><table className="mt-7 w-full border-collapse text-sm"><thead><tr className="bg-slate-100 text-left"><th className="border p-2">No</th><th className="border p-2">Program</th><th className="border p-2">Jumlah Sesi</th><th className="border p-2">Honor / Sesi</th><th className="border p-2">Subtotal</th></tr></thead><tbody>{slip.rows.map((r:any,i:number)=><tr key={i}><td className="border p-2">{i+1}</td><td className="border p-2">{r.program}</td><td className="border p-2">{r.sessions} sesi</td><td className="border p-2">{formatRupiah(r.rate)}</td><td className="border p-2">{formatRupiah(r.subtotal)}</td></tr>)}</tbody></table><div className="mt-5 border p-3 text-sm"><div className="flex justify-between"><b>TOTAL SESI</b><b>{slip.totalSessions} sesi</b></div></div><div className="flex justify-between bg-navy-900 px-4 py-3 text-sm font-bold text-white"><span>TOTAL HONOR</span><span>{formatRupiah(slip.totalHonor)}</span></div><div className="mt-12 text-right text-sm">{slip.settings.location||''}, {printed}</div><div className="mt-7 grid grid-cols-2 text-sm"><div><p>Penanggung Jawab</p><div className="h-24"/><p className="font-bold">{slip.settings.signatoryName||''}</p><p>{slip.settings.signatoryTitle||''}</p></div><div className="text-right"><p>Tentor</p><div className="h-24"/><p className="font-bold">{slip.tutor.name}</p><p>{slip.tutor.title||''}</p></div></div></article></div></div>;
}
