import { Router, Request, Response } from 'express';
import { requireAuth } from '../middleware/auth';
import { handleError } from '../utils/errors';
import { resolveTutorIdForUser } from '../services/sessionService';
import { buildHonorSlip, renderHonorSlipPdf } from '../services/honorSlipService';
const router=Router();
router.get('/slip-summary', requireAuth, async(req:Request,res:Response)=>{ let tutorId=typeof req.query.tutorId==='string'?req.query.tutorId:''; const month=Number(req.query.month),year=Number(req.query.year); if(!Number.isInteger(month)||month<1||month>12||!Number.isInteger(year)||year<2000)return res.status(400).json({error:'Validation error',message:'Bulan dan tahun tidak valid.'}); try { if(req.user!.role==='TENTOR') { const own=await resolveTutorIdForUser(req.user!.userId); if(!own || (tutorId && tutorId!==own)) return res.status(403).json({error:'Forbidden',message:'Anda hanya dapat melihat honor sendiri.'}); tutorId=own; } if(req.user!.role!=='ADMIN'&&req.user!.role!=='TENTOR') return res.status(403).json({error:'Forbidden'}); if(!tutorId)return res.status(400).json({error:'Validation error',message:'Tentor wajib diisi.'}); res.json({success:true,data:await buildHonorSlip(tutorId,month,year)}); }catch(e){handleError(e,res);} });
router.get('/slip.pdf', requireAuth, async(req:Request,res:Response)=>{ let tutorId=typeof req.query.tutorId==='string'?req.query.tutorId:''; const month=Number(req.query.month),year=Number(req.query.year); if(!Number.isInteger(month)||month<1||month>12||!Number.isInteger(year)||year<2000)return res.status(400).json({error:'Validation error',message:'Bulan dan tahun tidak valid.'}); try { if(req.user!.role==='TENTOR') { const own=await resolveTutorIdForUser(req.user!.userId); if(!own || (tutorId && tutorId!==own)) return res.status(403).json({error:'Forbidden',message:'Anda hanya dapat mengunduh slip honor sendiri.'}); tutorId=own; } if(req.user!.role!=='ADMIN'&&req.user!.role!=='TENTOR') return res.status(403).json({error:'Forbidden'}); if(!tutorId) return res.status(400).json({error:'Validation error',message:'Tentor wajib diisi.'}); const slip=await buildHonorSlip(tutorId,month,year); res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="slip-honor-${month}-${year}.pdf"`);res.send(renderHonorSlipPdf(slip)); } catch(e){handleError(e,res);} });
export default router;
