"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import api from "@/lib/api";
import EmptyState from "@/components/EmptyState";
import { StatusBadge, TypeBadge } from "@/components/StatusBadge";
import { formatRupiah } from "@/lib/format";
import { IconCheckCircle, IconChevronRight, IconClasses, IconPrivate, IconReport, IconSchedule, IconStudent, IconTutor } from "@/components/icons";

type Current = { todaySessionsCount:number;pendingValidationsCount:number;lowQuotaPackages:Array<{id:string;quotaRemaining:number;quotaTotal:number;packageName:string|null;student:{name:string}}> ;activeTutorsCount:number;activeStudentsCount:number;todaySessions:Array<any> };
type Monthly = { estimatedHonor:number;completedSessions:number;regularSessions:number;privateSessions:number;weekly:Array<{startDay:number;endDay:number;count:number}> };
const monthLabel=(year:number,month:number)=>new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(year,month-1,1));
const time=(v?:string)=>v?new Date(v).toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"}):"-";

export default function AdminDashboardPage(){
 const now=new Date(),[period,setPeriod]=useState({year:now.getFullYear(),month:now.getMonth()+1}),[current,setCurrent]=useState<Current|null>(null),[monthly,setMonthly]=useState<Monthly|null>(null),[loading,setLoading]=useState(true),[monthLoading,setMonthLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{api.get("/dashboard/admin").then(r=>setCurrent(r.data.data)).catch(()=>setError("Gagal memuat dashboard.")).finally(()=>setLoading(false));},[]);
 useEffect(()=>{setMonthLoading(true);api.get("/dashboard/admin/monthly",{params:period}).then(r=>setMonthly(r.data.data)).catch(()=>setMonthly(null)).finally(()=>setMonthLoading(false));},[period]);
 if(loading)return <div className="space-y-5"><div className="h-14 w-80 animate-pulse rounded bg-gray-200"/><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{Array.from({length:4},(_,i)=><div key={i} className="h-28 animate-pulse rounded-xl bg-gray-200"/>)}</div></div>;
 if(error||!current)return <EmptyState title="Dashboard" message={error||"Data dashboard tidak tersedia."}/>;
 const max=Math.max(...(monthly?.weekly.map(w=>w.count)||[0]),1), actions: Array<{href:string;label:string;icon:typeof IconSchedule}>=[{href:'/admin/schedules',label:'Tambah Jadwal',icon:IconSchedule},{href:'/admin/students',label:'Tambah Siswa',icon:IconStudent},{href:'/admin/tutors',label:'Tambah Tentor',icon:IconTutor},{href:'/admin/classes',label:'Tambah Kelas',icon:IconClasses}];
 const kpis=[['Tentor Aktif',current.activeTutorsCount,'tentor',IconTutor],['Siswa Aktif',current.activeStudentsCount,'siswa',IconStudent],['Sesi Hari Ini',current.todaySessionsCount,'sesi terjadwal',IconSchedule]] as const;
 return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-[22px] font-bold text-navy-900">Dashboard</h1><p className="text-sm text-gray-500">Ringkasan aktivitas dan kondisi operasional.</p></div><p className="text-sm text-gray-500">{new Intl.DateTimeFormat('id-ID',{dateStyle:'long'}).format(now)}</p></div>
 <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(([l,v,h,I])=><Kpi key={l} label={l} value={v} helper={h} icon={<I className="h-5 w-5"/>}/>)}<Kpi label="Estimasi Honor" value={monthLoading?'…':formatRupiah(monthly?.estimatedHonor||0)} helper={`${monthLabel(period.year,period.month)} · ${monthly?.completedSessions||0} sesi selesai`} icon={<IconReport className="h-5 w-5"/>}/></div>
 <div className="grid gap-5 lg:grid-cols-3"><Card title="Aktivitas Hari Ini" link="/admin/schedules" className="lg:col-span-2">{current.todaySessions.length?<div className="overflow-x-auto"><table className="w-full min-w-[640px] text-sm"><thead className="bg-slate-50 text-left text-xs text-gray-500"><tr><th className="p-3">Jam</th><th>Tentor</th><th>Program</th><th>Kelas / Siswa</th><th>Mapel</th><th>Status</th></tr></thead><tbody>{current.todaySessions.map(s=><tr key={s.id} className="border-t"><td className="p-3">{time(s.startTime||s.schedule?.startTime)}</td><td>{s.tutor.name}</td><td><TypeBadge type={s.sessionType}/></td><td>{s.sessionType==='REGULAR'?s.class?.name:s.student?.name}</td><td>{s.subject?.name||'-'}</td><td><StatusBadge status={s.status}/></td></tr>)}</tbody></table></div>:<EmptyState message="Belum ada aktivitas mengajar hari ini."/>}</Card><Card title="Perlu Perhatian">{current.pendingValidationsCount||current.lowQuotaPackages.length?<div className="divide-y">{current.pendingValidationsCount>0&&<Alert href="/admin/validations" title={`${current.pendingValidationsCount} sesi menunggu validasi`} text="Periksa sebelum masuk rekap honor."/>}{current.lowQuotaPackages.length>0&&<Alert href="#paket-menipis" title={`${current.lowQuotaPackages.length} paket privat hampir habis`} text="Sisa sesi mencapai batas peringatan."/>}</div>:<EmptyState title="Semua terkendali" message="Tidak ada item yang memerlukan tindakan." icon={<IconCheckCircle className="h-4 w-4"/>}/>}</Card></div>
 <div className="grid gap-5 lg:grid-cols-3"><Card title="Ringkasan Periode" className="lg:col-span-2" action={<input type="month" value={`${period.year}-${String(period.month).padStart(2,'0')}`} onChange={e=>{const [year,month]=e.target.value.split('-').map(Number);if(year&&month)setPeriod({year,month});}} className="rounded border px-2 py-1 text-sm"/>}>{monthLoading?<div className="h-36 animate-pulse rounded bg-gray-100"/>:<div className="grid gap-4 md:grid-cols-[1fr_220px]"><div><p className="font-semibold">Aktivitas Mengajar</p><p className="text-xs text-gray-500">Total sesi selesai per minggu</p><div className="mt-5 flex h-32 items-end justify-around gap-3">{monthly?.weekly.map(w=><div key={w.startDay} className="flex h-full flex-1 flex-col justify-end text-center text-xs"><b>{w.count}</b><div className="mt-1 bg-blue-600" style={{height:`${Math.max(4,w.count/max*90)}px`}}/><span className="mt-2 text-gray-500">{w.startDay}–{w.endDay}</span></div>)}</div></div><div className="space-y-2">{[['Total Sesi Selesai',monthly?.completedSessions],['Reguler',monthly?.regularSessions],['Privat',monthly?.privateSessions]].map(([l,v])=><div key={String(l)} className="rounded border p-3 text-sm"><p className="text-gray-500">{l}</p><b className="text-lg">{v||0} sesi</b></div>)}</div></div>}</Card><Card title="Aksi Cepat">{actions.map(({href,label,icon:Icon})=><Link key={label} href={href} className="flex items-center gap-3 border-b px-2 py-3 text-sm last:border-0"><Icon className="h-4 w-4"/><span className="flex-1">{label}</span><IconChevronRight className="h-4 w-4"/></Link>)}</Card></div>
 <Card title="Paket Privat Hampir Habis" subtitle="Paket siswa dengan sisa maksimal batas peringatan." id="paket-menipis">{current.lowQuotaPackages.length?<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="bg-slate-50 text-left text-xs text-gray-500"><tr><th className="p-3">Siswa</th><th>Program</th><th>Paket</th><th>Terpakai</th><th>Sisa Sesi</th><th>Status</th></tr></thead><tbody>{current.lowQuotaPackages.map(p=><tr key={p.id} className="border-t"><td className="p-3">{p.student.name}</td><td><TypeBadge type="PRIVATE"/></td><td>{p.quotaTotal} sesi</td><td>{p.quotaTotal-p.quotaRemaining} sesi</td><td className="text-red-600">{p.quotaRemaining} sesi</td><td><span className="rounded-full bg-red-50 px-2 py-1 text-xs text-red-600">Hampir Habis</span></td></tr>)}</tbody></table></div>:<EmptyState title="Kuota masih aman" message="Belum ada paket privat yang mencapai batas peringatan."/>}</Card></div>;
}
function Kpi({label,value,helper,icon}:{label:string;value:any;helper:string;icon:React.ReactNode}){return <div className="flex gap-3 rounded-xl border bg-white p-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-navy-50 text-navy-800">{icon}</span><div><p className="text-sm text-gray-500">{label}</p><b className="text-xl text-navy-900">{value}</b><p className="text-xs text-gray-500">{helper}</p></div></div>}
function Card({title,children,link,action,className='',subtitle,id}:{title:string;children:React.ReactNode;link?:string;action?:React.ReactNode;className?:string;subtitle?:string;id?:string}){return <section id={id} className={`rounded-xl border bg-white p-4 ${className}`}><div className="mb-3 flex items-center justify-between gap-3"><div><h2 className="font-semibold text-navy-900">{title}</h2>{subtitle&&<p className="text-xs text-gray-500">{subtitle}</p>}</div>{action||link&&<Link href={link} className="text-xs font-medium text-blue-600">Lihat Semua →</Link>}</div>{children}</section>}
function Alert({href,title,text}:{href:string;title:string;text:string}){return <Link href={href} className="flex gap-3 py-3 text-sm"><span className="text-red-500">●</span><span className="flex-1"><b>{title}</b><small className="mt-1 block text-gray-500">{text}</small></span><IconChevronRight className="h-4 w-4 text-gray-400"/></Link>}
