'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import api from '@/lib/api';
import { formatDate, formatRupiah } from '@/lib/format';

export default function TutorHonorDetailPage() {
  const params=useParams<{tutorId:string}>(); const search=useSearchParams(); const [data,setData]=useState<any>(null); const [sessions,setSessions]=useState<any[]>([]); const [error,setError]=useState(''); const month=Number(search.get('month')||new Date().getMonth()+1); const year=Number(search.get('year')||new Date().getFullYear());
  const period=new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date(year,month-1,1));
  useEffect(()=>{Promise.all([api.get('/honor/slip-summary',{params:{tutorId:params.tutorId,month,year}}),api.get('/sessions',{params:{tutorId:params.tutorId,startDate:`${year}-${String(month).padStart(2,'0')}-01`,endDate:new Date(year,month,0).toISOString().slice(0,10),status:'COMPLETED'}})]).then(([summary,detail])=>{setData(summary.data.data);setSessions(detail.data.data.filter((s:any)=>s.status==='COMPLETED'));}).catch((e:any)=>setError(e.response?.data?.message||'Gagal memuat detail honor.'));},[params.tutorId,month,year]);
  async function pdf(){try{const r=await api.get('/honor/slip.pdf',{params:{tutorId:params.tutorId,month,year},responseType:'blob'});const url=URL.createObjectURL(new Blob([r.data],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download='slip-honor.pdf';a.click();URL.revokeObjectURL(url);}catch(e:any){setError(e.response?.data?.message||'Gagal membuat Slip Honor.');}}
  if(error)return <div className="space-y-3"><Link href="/admin/recap" className="text-sm text-navy-900">← Kembali ke Rekap</Link><p className="rounded bg-red-50 p-3 text-sm text-red-600">{error}</p></div>;
  if(!data)return <p className="text-sm text-gray-500">Memuat detail honor...</p>;
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/admin/recap" className="text-sm text-navy-900">← Kembali ke Rekap</Link><h1 className="mt-2 text-xl font-semibold">Detail Honor Tentor</h1></div><div className="flex gap-2"><Link href={`/admin/recap/slip/${params.tutorId}?month=${month}&year=${year}`} className="rounded border border-navy-900 px-4 py-2 text-sm text-navy-900">Preview Slip</Link><button onClick={pdf} className="rounded bg-navy-900 px-4 py-2 text-sm text-white">Unduh PDF</button></div></div><section className="rounded-lg border bg-navy-900 p-5 text-white"><p className="text-sm text-navy-200">{period}</p><h2 className="mt-1 text-xl font-semibold">{data.tutor.name}{data.tutor.title?`, ${data.tutor.title}`:''}</h2><div className="mt-4 grid grid-cols-2 gap-4"><div><p className="text-xs text-navy-200">Total Sesi Selesai</p><p className="text-2xl font-semibold">{data.totalSessions}</p></div><div><p className="text-xs text-navy-200">Total Honor</p><p className="text-2xl font-semibold">{formatRupiah(data.totalHonor)}</p></div></div></section><div className="grid gap-4 lg:grid-cols-3"><section className="rounded-lg border bg-white p-4"><h2 className="font-medium">Ringkasan Program</h2><div className="mt-3 space-y-2">{data.rows.map((r:any,i:number)=><div key={i} className="flex justify-between rounded bg-slate-50 p-2 text-sm"><span>{r.program}<br/><small>{r.sessions} sesi · {formatRupiah(r.rate)}</small></span><b>{formatRupiah(r.subtotal)}</b></div>)}</div></section><section className="overflow-x-auto rounded-lg border bg-white lg:col-span-2"><table className="w-full text-sm"><thead><tr className="border-b text-left text-gray-500"><th className="p-3">Tanggal</th><th>Program</th><th>Kelas / Siswa</th><th>Mapel</th><th>Jam</th><th>Tarif / Sesi</th><th>Honor</th></tr></thead><tbody>{sessions.map(s=><tr key={s.id} className="border-b"><td className="p-3">{formatDate(s.sessionDate)}</td><td>{s.sessionType==='REGULAR'?'Reguler':'Privat'}</td><td>{s.sessionType==='REGULAR'?s.class?.name:s.student?.name}</td><td>{s.subject?.name||'-'}</td><td>{s.schedule?.startTime?new Date(s.schedule.startTime).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}):'-'}</td><td>{formatRupiah(s.honorRateSnapshot)}</td><td>{formatRupiah(s.honorRateSnapshot)}</td></tr>)}</tbody></table></section></div></div>;
}
