"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import api, { errorMessage } from "@/lib/api";
import PageHeader from "@/components/PageHeader";
import Modal from "@/components/Modal";
import { IconEye, IconPlus, IconPrint, IconReport, IconSearch, IconTrash } from "@/components/icons";

type Letter = { id: string; letterNumber: string; studentName: string; programName: string; startDate: string; endDate: string; letterDate: string; _count: { schedules: number } };
const dateText = (value: string) => new Intl.DateTimeFormat("id-ID", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(value));
export default function StudentLettersPage() {
  const [letters, setLetters] = useState<Letter[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null), [search, setSearch] = useState(""), [period, setPeriod] = useState(""), [removeTarget, setRemoveTarget] = useState<Letter | null>(null), [deleting, setDeleting] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await api.get("/student-letters"); setLetters(response.data.data); } catch (cause) { setError(errorMessage(cause, "Gagal memuat data surat.")); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const periods = useMemo(() => Array.from(new Set(letters.map((letter) => new Date(letter.letterDate).toISOString().slice(0, 7)))).sort().reverse(), [letters]);
  const visible = useMemo(() => letters.filter((letter) => `${letter.letterNumber} ${letter.studentName}`.toLowerCase().includes(search.toLowerCase()) && (!period || letter.letterDate.slice(0, 7) === period)), [letters, period, search]);
  async function destroy() { if (!removeTarget) return; setDeleting(true); try { await api.delete(`/student-letters/${removeTarget.id}`); setRemoveTarget(null); await load(); } catch (cause) { setError(errorMessage(cause, "Gagal menghapus surat.")); setRemoveTarget(null); } finally { setDeleting(false); } }
  return <div><nav aria-label="Breadcrumb" className="mb-3 flex gap-2 text-xs text-gray-400"><span>Admin</span><span>/</span><span className="text-gray-600">Surat Siswa</span></nav><PageHeader title="Surat Siswa" description="Kelola surat keterangan dan jadwal administratif siswa." action={<Link href="/admin/student-letters/new" className="inline-flex items-center gap-2 rounded-lg bg-navy-900 px-4 py-2.5 text-sm font-medium text-white shadow-sm hover:bg-navy-800"><IconPlus className="h-4 w-4" />Buat Surat</Link>} />
    <section className="mb-5 rounded-xl border border-gray-200 bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative min-w-0 flex-1"><span className="sr-only">Cari surat</span><IconSearch className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari nomor surat atau nama siswa..." className="h-10 w-full rounded-lg border border-gray-300 pl-9 pr-3 text-sm outline-none focus:border-navy-500 focus:ring-2 focus:ring-navy-100" /></label><select value={period} onChange={(event) => setPeriod(event.target.value)} className="h-10 rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-700"><option value="">Semua Periode</option>{periods.map((value) => <option key={value} value={value}>{new Intl.DateTimeFormat("id-ID", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}-01T00:00:00Z`))}</option>)}</select></div></section>
    {error ? <section className="rounded-xl border border-red-200 bg-red-50 p-5 text-sm text-red-800"><p>{error}</p><button onClick={load} className="mt-3 rounded-md border border-red-300 bg-white px-3 py-1.5 font-medium">Coba Lagi</button></section> : <section className="overflow-x-auto rounded-xl border border-gray-200 bg-white shadow-sm"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-gray-200 bg-gray-50/80 text-left text-[11px] font-semibold uppercase tracking-wide text-gray-500"><th className="px-5 py-3">No.</th><th className="px-4 py-3">Nomor Surat</th><th className="px-4 py-3">Siswa</th><th className="px-4 py-3">Program</th><th className="px-4 py-3">Periode</th><th className="px-4 py-3">Tanggal Surat</th><th className="px-4 py-3">Pertemuan</th><th className="px-5 py-3 text-right">Aksi</th></tr></thead><tbody>{loading ? Array.from({ length: 5 }).map((_, index) => <tr key={index} className="border-b"><td colSpan={8} className="px-5 py-4"><div className="h-4 animate-pulse rounded bg-gray-100" /></td></tr>) : visible.length ? visible.map((letter, index) => <tr key={letter.id} className="border-b border-gray-100 last:border-0 hover:bg-slate-50/70"><td className="px-5 py-3.5 text-xs text-gray-500">{index + 1}</td><td className="px-4 py-3.5 font-medium text-gray-900">{letter.letterNumber}</td><td className="px-4 py-3.5">{letter.studentName}</td><td className="px-4 py-3.5 text-xs">{letter.programName}</td><td className="px-4 py-3.5 text-xs">{dateText(letter.startDate)} - {dateText(letter.endDate)}</td><td className="px-4 py-3.5 text-xs">{dateText(letter.letterDate)}</td><td className="px-4 py-3.5 text-xs">{letter._count.schedules} pertemuan</td><td className="px-5 py-3.5"><div className="flex justify-end gap-1"><Link href={`/admin/student-letters/${letter.id}`} aria-label="Lihat detail surat" title="Lihat detail" className="rounded-md p-2 text-navy-700 hover:bg-navy-50"><IconEye className="h-4 w-4" /></Link><a href={`/admin/student-letters/${letter.id}/print`} target="_blank" rel="noreferrer" aria-label="Cetak atau simpan PDF" title="Cetak / Simpan PDF" className="rounded-md p-2 text-navy-700 hover:bg-navy-50"><IconPrint className="h-4 w-4" /></a><button onClick={() => setRemoveTarget(letter)} aria-label="Hapus surat" title="Hapus surat" className="rounded-md p-2 text-red-700 hover:bg-red-50"><IconTrash className="h-4 w-4" /></button></div></td></tr>) : <tr><td colSpan={8} className="px-5 py-14 text-center"><IconReport className="mx-auto h-8 w-8 text-gray-300" /><p className="mt-3 font-medium text-gray-700">Belum ada surat siswa</p><p className="mt-1 text-xs text-gray-500">Surat yang dibuat akan tampil di halaman ini.</p><Link href="/admin/student-letters/new" className="mt-4 inline-flex items-center gap-1 rounded-lg bg-navy-900 px-3 py-2 text-xs font-medium text-white"><IconPlus className="h-3.5 w-3.5" /> Buat Surat</Link></td></tr>}</tbody></table></section>}
    {removeTarget && <Modal title="Hapus Surat?" onClose={() => !deleting && setRemoveTarget(null)}><p className="text-sm leading-6 text-gray-600">Surat ini akan dihapus beserta jadwal administratifnya. Tindakan ini tidak dapat dibatalkan.</p><div className="mt-5 flex justify-end gap-2"><button disabled={deleting} onClick={() => setRemoveTarget(null)} className="rounded-lg border border-gray-300 px-4 py-2 text-sm">Batal</button><button disabled={deleting} onClick={destroy} className="rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-60">{deleting ? "Menghapus..." : "Hapus Surat"}</button></div></Modal>}
  </div>;
}
